[package]
name = "climbing"
version = "0.1.0"
authors = ["deranson <deranson@uniqfi.one>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
